language: node_js
node_js:
  - "0.10"
install: "npm -g install jshint"
before_script: 
  - "wget http://emilkm.hp.af.cm/php-server.tar.gz"
  - "tar -zxvf php-server.tar.gz"
  - "chmod 777 server/php"
  - "server/php -S localhost:8000 2>&1 > php.log &"
  - sleep 3
  - "curl http://localhost:8000/README.md"
script: "/bin/bash ./travis-ci.sh"